### ISSUE TITLE
Score is 0 is it a [Bug] or is it not implemented yet?

### ISSUE THREAD

**Issue by umarfarooqumzen** [Udayraj123/OMRChecker#114] opened 2022-12-22 21:45 UTC
I have tried with every sample and all i get is score=0 for every run what is the issue, not a python guy so apologies in advance if i am being wrong about it.

**Comment by Udayraj123** [comment] 2022-12-28 04:29
@umarfarooqumzen it's not implemented yet. Currently we let the users calculate the score using excel formulae.

@Rohan-G has discussed a generalized schema for an evaluation schema in https://github.com/Udayraj123/OMRChecker/issues/89

**Comment by Udayraj123** [comment] 2022-12-28 04:30
Closing as duplicate of #89 
@umarfarooqumzen feel free to continue this discussion there.

**Closed by Udayraj123** 2022-12-28 04:30 UTC
